name: HelpPages
version: ${project.version}
description: Make your own Help Pages!
author: PaulBGD and Community
main: me.paulbgd.bukkit.HP.HelpPages

commands:
  help:
    description: View the help menu!
    usage: /help <page> [submenu [submenu]]
